<?php
	$url = $this->url ( 'certificate', array (
		'action' => 'deleteCertificate',
		'id' => $this->id 
	) );
?>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
     		<h4 class="modal-title" id="myModalLabel">Delete Certificate</h4>
        </div>
     	<div id="modal-body" class="modal-body">
     		<Span id="lblName">Are you sure want to delete?</Span>
             <input class="form-control margin-left50" type="text" id="txtCategoryDel" 
             disabled="disabled" value="<?php echo $this->title; ?>" >   
        </div>
        <div class="modal-footer">
			<form action="<?php echo $url; ?>" method="post">
				<div>
					<input type="hidden" name="id" value="<?php echo (int) $this->id; ?>" />
					<input type="submit" name="del" value="Yes" class="btn btn-primary" />
					<input type="submit" name="del" value="No" class="btn btn-primary" />
				</div>
			</form>
		</div>
    </div>
</div>