<?php
$title = 'Delete Certificate';
$this->headTitle ( $title );
?>
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title" id="myModalLabel"><?php echo $title;?></h4>
		</div>
		<div id="modal-body" class="modal-body">
		    <Span id="lblName">Please Select Atleast One Test For Deletion?</Span>
		</div>
		<div class="modal-footer">
		    <input type="button" class="btn margin-left50 margin-top10" value="Ok" data-dismiss="modal" />
		</div>
	</div>
</div>
