<?php
	$url = $this->url ( 'certificate', array (
		'action' => 'multiDeleteCertificate'
	) );
?>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
     		<h4 class="modal-title" id="myModalLabel">Multi Delete Certificate</h4>
        </div>
     	<div id="modal-body" class="modal-body">
     		<span id="lblName">Are you sure to delete selected Tests?</span>  
        </div>
        <div class="modal-footer">
			<form action="<?php echo $url; ?>" method="post">
				<div>
					<input type="hidden" name="ids" value="<?php echo $this->ids; ?>" />
					<input type="submit" name="del" value="Yes" class="btn btn-primary" />
					<input type="submit" name="del" value="No" class="btn btn-primary" />
				</div>
			</form>
		</div>
    </div>
</div>