<?php
/*
* @author : Leena,Vijay
* @desc : View For Adding Test To Test module
* @created on : 30-06-2014
* ---------------------------------------------
* @modified on :
*
*
*
*/
?>
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"
				aria-hidden="true">&times;</button>
			<h4 class="modal-title" id="myModalLabel">Add New Test</h4>
		</div>
                 <?php
					 $this->form->setAttribute ( 'action', $this->url ( 'test', array (
										   'action' => 'add' 
										 ) ) );
                   
					 $this->form->prepare ();
					 echo $this->form ()->openTag ( $this->form );
				 ?>
                 <div id="modal-body" class="modal-body">
                 <span id="lblName">Test Name</span>
               <?php
					echo $this->formHidden ( $this->form->get ( 'id' ) );
				    echo $this->formelement($this->form->get('name'));
				    echo "<span id='testNameError' class=''>".$this->formElementErrors($this->form->get('name'))."</span>";
				    ?>
				     <div id="errTestName" class="testErrors"></div>
				     <?php
				    echo("</br>");
			   ?>
			      <span id="lblNameTestDesc">Test Description</span>
			   <?php
					echo $this->formelement($this->form->get('description'));
					echo "<span id='testDescError' class=''>".$this->formElementErrors($this->form->get('description'))."</span>";
			   ?>
			   <div id="errTestDesc" class="testErrors"></div>
			 
        
		<div class="modal-footer">
		    <?php
				    echo $this->formSubmit ( $this->form->get ( 'submit' ) );
					echo $this->form ()->closeTag ();
			?>

        	<button type="button" class="btn"
				data-dismiss="modal">Close</button>
			<!-- <input type="button" id="addbtn" class="btn btn-primary" name = "submit" value = "Add"> -->
		</div>
	</div>
</div>

<script>
$(document).ready(function(){
  $("#testName").on("keypress", function(e) {
  if (e.which === 32 && !this.value.length)
      e.preventDefault();
  });
   $("#testDesc").on("keypress", function(e) {
  if (e.which === 32 && !this.value.length)
      e.preventDefault();
  });
});

</script>