<?php
/*
* @author : Leena,Vijay
* @desc : View For Editing Test To Test module
* @created on : 30-06-2014
* ---------------------------------------------
* @modified on :
*
*
*
*/
$title = 'Edit Test';
$this->headtitle ( $title );
?>
<div class="modal-dialog">
<div class="modal-content">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title" id="myModalLabel"><?php echo $title;?></h4>
	</div>
	<?php
			$this->form->setAttribute ( 'action', $this->url ( 'test', array (
					'action' => 'edit',
					'id' => $this->id
			) ) );
            $this->form->setAttribute('id','editTest');
			$this->form->prepare ();
			echo $this->form ()->openTag ( $this->form );
	?>
	<div id="modal-body" class="modal-body">
       <span id="lblName">Test Name</span>
	<?php 
			echo $this->formhidden ( $this->form->get ( 'id' ) );
			echo $this->formelement ( $this->form->get ( 'name' ) );
			echo "<span id='testNameError' class=''>".$this->formElementErrors($this->form->get('name'))."</span>";
	?>
			<div id="errTestName" class="testErrors"></div>
	<?php
			echo ("</br>");
	?>
	    <span id="lblNameTestDesc">Test Description</span>
	<?php 
			echo $this->formelement ( $this->form->get ( 'description' ) );
			echo "<span id='testDescError' class=''>".$this->formElementErrors($this->form->get('description'))."</span>";
	?>
			<div id="errTestDesc" class="testErrors"></div>
	<?php
			echo ("</br>");
			$this->form->get('submit')->setAttribute('id', 'editSubmit');
			// echo $this->formcollection($form);
			$this->form->get('submit')->setAttribute('id', 'submitEdit');
	?>
	</div>
	<div class="modal-footer">
	    <?php
				echo $this->formsubmit ( $this->form->get ( 'submit' ) );
				echo $this->form ()->closeTag ();
		?>
		<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
			<!-- <button type="button" class="btn btn-primary" name="abc">Save changes</button> -->
	</div>
  </div>
</div>
