<?php
$url  = "";
$emailIds = "";
if(isset($arrData) && !empty($arrData)) {
	$url = $arrData['url'];
	$emailIds = $arrData['emailIds'];
}
?>

<style type="text/css">
	#loading{display:none; }
</style>

<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Success</h4>
        </div>
        <div id="modal-body" class="modal-body">
        <h4 id="pln" class="fontapply">Link Created</h4>
        <input type="text" id="txtLink" readonly="readonly" class="form-control" 
        value="<?php echo $url?>">
		<h4 class="fontapply" id="pln-small">
		<?php if(isset($emailIds) && !empty($emailIds)) {?>
			
			<div id="loading">
				<p class="text-info">
            	Sending Mail to the recipients, Please Wait....
            		<img id="loadingImageReg" src="<?php echo $this->basePath()?>/img/loading.gif" alt="Loading"/>
        		</p>
        	</div>
		
		<?php } else { ?>

			Note: use this link to assign test

		<?php } ?>
		</h4>
		<input type="button" id="btnOk" class="btn" value="OK">
		</div>
	</div>
</div>