<?php
/*
* @author : Leena,Vijay
* @desc : View For Deleting Test From Test module
* @created on : 30-06-2014
* ---------------------------------------------
* @modified on :
*
*
*
*/
$title = 'Delete Test';
$this->headTitle ( $title );
?>
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title" id="myModalLabel"><?php echo $title;?></h4>
		</div>
		<div id="modal-body" class="modal-body">
		    <Span id="lblName">Please Select Atleast One Test For Deletion?</Span>
			<!--  <input type="text" class="form-control margin-left50" 
				   value="<?php //echo $this->escapeHtml($test->name);?>" disabled="disabled" name="txtCategoryDel"/>-->
		
		</div>
		<div class="modal-footer">
		    <input type="button" class="btn margin-left50 margin-top10" value="Ok" data-dismiss="modal" />
			<!-- <form action="<?php //echo $url; ?>" method="post">
			<div>
		    	<input type = "hidden" value = "<?php echo $this->testId;?>" name = 'tid'>
				<input type="submit" name="del" value="Yes" class="btn btn-primary" />
				<input type="submit" name="del" value="No" class="btn btn-primary" />
			</div>
			</form>-->
		</div>
	</div>
</div>
