<?php
/*
* @author : Vikash,Leena
*
* @created on : 12-08-2014
* ---------------------------------------------
* @modified on :
*
*
*
*/
$title = 'Delete User';
$this->headTitle ( $title );
?>
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title" id="myModalLabel"><?php echo $title;?></h4>
		</div>
		<div id="modal-body" class="modal-body">
		    <Span id="lblName">Are you sure want to delete this User?</Span>
			
		<?php

			$url = $this->url ( 'user', array (
								'action' => 'deleteUserConfirm',
								'id' => $this->id 
							   ) );
		?>
		<form action="<?php echo $url; ?>" method="post">
		<div>
			<input type="hidden" name="id" value="<?php echo (int) $user->id; ?>" />
			<input type="submit" name="del" value="Confirm" class="btn btn-primary margin-top20 margin-left50" />
			<!-- <input type="submit" name="del" value="No" class="btn btn-primary margin-top20 " /> -->
		</div>
		</form>
		</div>
		<!-- <div class="modal-footer">
		
		</div> -->
	</div>
</div>

